controllers_front:
    resource: ../../src/Controller/Front
    type: annotation
    name_prefix: 'front_'

controllers_back:
    resource: ../../src/Controller/Back
    type: annotation
    prefix: '/admin'
    name_prefix: 'back_'

kernel:
    resource: ../../src/Kernel.php
    type: annotation
